name: Coverage

on:
  release:
    types: ["published", "unpublished", "prereleased"]

permissions: read-all

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up docker environment
        run: docker compose -f testing.docker-compose.yaml up -d

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverpkg ./... -coverprofile coverage.txt -covermode atomic ./...
      
      - uses: codecov/codecov-action@v3

      - name: Clean docker environment
        run: docker compose -f testing.docker-compose.yaml down --rmi all -v --remove-orphans